version: '3.4'

services: 
  nodeweb:
    container_name: nodeweb
    image: nodeweb
    build:
      context: nodeweb
      dockerfile: ./nodeweb/Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 7777:3000
  
  angularfront:
    container_name: angularfront
    image: angularfront
    build:
      context: angularfront
      dockerfile: ./angularfront/Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4200:80
    depends_on: 
      - nodeweb
